CREATE TABLE IF NOT EXISTS "claritise_blog_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "claritise_blog_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" varchar(256) NOT NULL,
	"title" varchar(256) NOT NULL,
	"content" varchar(20000) NOT NULL,
	"excerpt" varchar(500),
	"published" boolean DEFAULT false NOT NULL,
	"published_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "claritise_blog_post_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "blog_post_slug_idx" ON "claritise_blog_post" USING btree ("slug");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "blog_post_published_idx" ON "claritise_blog_post" USING btree ("published");